### ISSUE TITLE
dependency conflict

### ISSUE THREAD

**Issue by nickyoungforu** [XiangLi1999/Diffusion-LM#12]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 1.8.0 requires huggingface-hub<0.1.0, but you have huggingface-hub 0.4.0 which is incompatible.

**Comment by nickyoungforu** [comment]
close

**Comment by Shiguang-Guo** [comment]
I have the same problem, how did you solve it?

**Comment by nickyoungforu** [comment]
> I have the same problem, how did you solve it?

pip install datasets==2.4.0
