### ISSUE TITLE
Missing `training_args.json` during training

### ISSUE THREAD

**Issue by ChorlingLau** [XiangLi1999/Diffusion-LM#13]
Thanks so much for making the code available!
I'm trying to run the example command in the README. However, it occurs the same error of missing a file named `training_args.json` during both Train Diffusion-LM and Contrallable Text Generation.
```
python scripts/run_train.py --diff_steps 2000 --model_arch transformer --lr 0.0001 --lr_anneal_steps 200000 --seed 102 --noise_schedule sqrt --in_channel 16 --modality e2e-tgt --submit no --padding_mode block --app "--predict_xstart True --training_mode e2e --vocab_size 821 --e2e_train ../datasets/e2e_data " --notes xstart_e2e

python train_run.py --experiment e2e-tgt-tree --app "--init_emb {path-to-diffusion-lm} --n_embd {16} --learned_emb yes " --pretrained_model bert-base-uncased --epoch 6 --bsz 10
```
Could you please tell me where the file is or how to make it?
Thanks a lot!

**Comment by XiangLi1999** [comment]
Hi, 
I think training_args.json will be generated as you run scripts/run_train.py 
Maybe you just need to create the directory.
