### ISSUE TITLE
Evaluating methods

### ISSUE THREAD

**Issue by Laney-cici** [XiangLi1999/Diffusion-LM#14]
Hi, I finished all commands that you provided, but I don't know how to evaluate the generated files.
I noticed that there is a script (Diffusion-LM/improved-diffusion/control_gen/eval_control.py) to evaluate, but I can't find "diffusion_lm/misc/self-attentive-parser" and "evaluate". Could you add them or reply here with evaluating method?
Thanks!

**Comment by XiangLi1999** [comment]
You could get the evaluation wrapper by cloning 
https://github.com/nikitakit/self-attentive-parser, I reuse their wrapper around the parse tree evaluation.
