### ISSUE TITLE
Error message when trying to train the model

### ISSUE THREAD

**Issue by JamesL404** [XiangLi1999/Diffusion-LM#32]
I receive this message when I tried to train the model: [''OPENAI_LOGDIR'' is not recognized as an internal or external command, operable program or batch file.]  Could anyone help me with this?

**Comment by XiangLi1999** [comment]
I think you want to prepend  OPENAI_LOGDIR=diffusion_models/your_file_name before python scripts/train.py

**Comment by JamesL404** [comment]
The same error shows up when I tried to prepend OPENAI_LOGDIR, and after I delete the OPENAI_LOGDIR from the command line, the error:  "TOKENIZERS_PARALLELISM" is not recognized as an internal or external command, operable program, or batch file. I have tried to reinstall anaconda and create a new environment, but they didn't fix the error at all.

**Comment by JamesL404** [comment]
No worries it works on the online GPU, thanks!
