### ISSUE TITLE
Where is the mask indicator to calculate the decoder loss?

### ISSUE THREAD

**Issue by smiles724** [XiangLi1999/Diffusion-LM#45]
Hi, you use `token_discrete_loss` to compute the decoder loss. However, it seems to include all cross-entropy losses for all input tokens, which may be unreasonable.

In contrast, should you exclude all PAD tokens in your decoder loss? 

![image](https://user-images.githubusercontent.com/39299863/199683655-c7d6c6ac-c1e3-4c5f-9a13-2b1cc69e5ff6.png)

**Comment by XiangLi1999** [comment]
Hi, 

Thanks for the question! 

We are doing this intentionally and assuming that these PAD tokens are part of the data distribution. So when Diffusion-LM wants to generate sentences of length < 64, it will generate the PAD tokens for the remaining spaces. 

Alternatively, if we don't do this during training, the model would learn to generate meaningless tokens after EOS token at generation time. One way to handle is to truncate anything after the EOS token, but we believe the current version is slightly cleaner. 

Hope this helps!

**Comment by smiles724** [comment]
Thanks for your reply. This is interesting and sounds reasonable!
