### ISSUE TITLE
Questions about the result of success rate of PPLM?

### ISSUE THREAD

**Issue by jiqimaoke** [XiangLi1999/Diffusion-LM#55]
Hello, thank you for your excellent work. 
When I tried to reimplement the success rate of PPLM in semantic control in the paper, I have problem in achieving the 9.9 point of the paper. Can you release your checkpoint and code of the PPLM baselines in your paper?
Thank you for your time!

**Comment by YANI-ALT** [comment]
@jiqimaoke Hello, I am trying to reproduce the PPLM baseline for semantic control as well ? Can you guide me as to what the setup is ? How to train the classifier and perform evaluation for the task ?

Thank you !

**Comment by jiqimaoke** [comment]
Sorry for replying so late. According to target_attribute.json, I used a 79-way classifier in PPLM and obtained a similar result with the paper.
