### ISSUE TITLE
Missing `control_gen/target_tree.json` file for infill script

### ISSUE THREAD

**Issue by jwkirchenbauer** [XiangLi1999/Diffusion-LM#9]
I'm trying to run the last example command in your README
```
python scripts/infill.py --model_path {path-to-diffusion-lm}  --model_arch transformer --eval_task_ 'control_tree' --use_ddim True  --notes "tree_adagrad" --eta 1. --verbose pipe
```
and with a few edits I get it to run up until the line for [loading the control_label_lst](https://github.com/XiangLi1999/Diffusion-LM/blob/344f447deaaa9eccc6c81ba859e05c2166d40fb4/improved-diffusion/scripts/infill.py#L330) for the tree task.

Could you add the `control_gen/target_tree.json` file or reply here with the file contents? I'm trying to get a minimum working execution of the entire pipeline for at least one task to better understand how you implemented the conditional denoising/generation using the embedded control sequence. With this file I think I can get the infill script to execute fully, which should help in this process.

Thanks!

**Comment by pl8787** [comment]
After a few edits to the code, I have the same question.

**Comment by Laney-cici** [comment]
I have the same question.

**Comment by XiangLi1999** [comment]
just pushed to the repo, all the control targets are here: https://github.com/XiangLi1999/Diffusion-LM/tree/main/datasets/control_target
